/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2012-02-16 10:57:39 -0500 (Thu, 16 Feb 2012) $
 * Revision:      $LastChangedRevision: 5361 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Iehr.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Iehr.Repc_mt000012ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Merged;
    using System;


    /**
     * <summary>ReportedBy</summary>
     * 
     * <remarks>REPC_MT000005CA.Informant: d:reported by 
     * <p>Indicates where the information that led to the recording 
     * of this information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>The original source of the 
     * information can be important in evaluating its accuracy and 
     * importance.</p> REPC_MT000003CA.Informant: c:reported by 
     * <p>Indicates where the information that led to the recording 
     * of this information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>ZPB2.5</p> <p>The original 
     * source of the information can be important in evaluating its 
     * accuracy and importance.</p> REPC_MT000001CA.Informant: 
     * d:reported by <p>Indicates where the information that led to 
     * the recording of this information came from. The possible 3 
     * sources of the information are: the patient, the patient's 
     * representative or a health-care provider.</p> <p>The 
     * original source of the information can be important in 
     * evaluating its accuracy and importance.</p> 
     * REPC_MT000013CA.Informant: d:reported by <p>Indicates where 
     * the information that led to the recording of this 
     * information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>The original source of the 
     * information can be important in evaluating its accuracy and 
     * importance.</p> REPC_MT000006CA.Informant: d:reported by 
     * <p>Indicates where the information that led to the recording 
     * of this information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>The original source of the 
     * information can be important in evaluating its accuracy and 
     * importance.</p> REPC_MT000007CA.Informant: reported by 
     * <p>Indicates where the information that led to the recording 
     * of this medical condition came from. The possible 3 sources 
     * of the information are: the patient, the patient's 
     * representative or a health-care provider.</p> <p>The 
     * original source of the information can be important in 
     * evaluating its accuracy and importance.</p> 
     * REPC_MT000012CA.Informant: d:reported by <p>Indicates where 
     * the information that led to the recording of this 
     * information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>The original source of the 
     * information can be important in evaluating its accuracy and 
     * importance.</p> REPC_MT000014CA.Informant: b:reported by 
     * <p>Indicates where the information that led to the recording 
     * of this information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>Allows for establishment 
     * of timelines between reported date and recorded date.</p> 
     * REPC_MT000009CA.Informant: d:reported by <p>Indicates where 
     * the information that led to the recording of this 
     * information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>The original source of the 
     * information can be important in evaluating its accuracy and 
     * importance.</p> REPC_MT000010CA.Informant: d:reported by 
     * <p>Indicates where the information that led to the recording 
     * of this information came from. The possible 3 sources of the 
     * information are: the patient, the patient's representative 
     * or a health-care provider.</p> <p>ZPB2.5</p> <p>The original 
     * source of the information can be important in evaluating its 
     * accuracy and importance.</p> REPC_MT000002CA.Informant: 
     * d:reported by <p>Indicates where the information that led to 
     * the recording of this information came from. The possible 3 
     * sources of the information are: the patient, the patient's 
     * representative or a health-care provider.</p> <p>The 
     * original source of the information can be important in 
     * evaluating its accuracy and importance.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"REPC_MT000001CA.Informant","REPC_MT000002CA.Informant","REPC_MT000003CA.Informant","REPC_MT000005CA.Informant","REPC_MT000006CA.Informant","REPC_MT000007CA.Informant","REPC_MT000009CA.Informant","REPC_MT000010CA.Informant","REPC_MT000012CA.Informant","REPC_MT000013CA.Informant","REPC_MT000014CA.Informant"})]
    public class ReportedBy : MessagePartBean {

        private TS time;
        private Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Iehr.Merged.IParty party;
        private Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Merged.IConsenter consenter;
        private Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Iehr.Repc_mt000012ca.IChoice choice;

        public ReportedBy() {
            this.time = new TSImpl();
        }
        /**
         * <summary>Reported Timestamp</summary>
         * 
         * <remarks><p>The date on which the medical condition was 
         * reported.</p> <p>Allows for establishment of timelines 
         * between condition onset date, reported date and recorded 
         * date.</p> Reported Date <p>The date on which the adverse 
         * reaction was reported.</p> <p>Allows for establishment of 
         * timelines between onset date, reported date and recorded 
         * date, and is therefore mandatory.</p> Reported Timestamp 
         * <p>The date on which the adverse reaction was reported.</p> 
         * <p>Allows for establishment of timelines between onset date, 
         * reported date and recorded date, and is therefore 
         * mandatory.</p> Reported Date <p>The date on which the 
         * medical condition was reported.</p> <p>Allows for 
         * establishment of timelines between onset date, reported date 
         * and recorded date, and is therefore mandatory.</p> Reported 
         * Date <p>The date on which the allergy/intolerance was 
         * reported.</p> <p>Allows for establishment of timelines 
         * between onset date, reported date and recorded date, and is 
         * therefore mandatory.</p> Reported date <p>The date on which 
         * the adverse reaction was reported.</p> <p>Allows for 
         * establishment of timelines between reaction onset date, 
         * reported date and recorded date, and is therefore 
         * mandatory.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"time"})]
        public PlatformDate Time {
            get { return this.time.Value; }
            set { this.time.Value = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"party"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Iehr.Merged.IParty Party {
            get { return this.party; }
            set { this.party = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"consenter"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Merged.IConsenter Consenter {
            get { return this.consenter; }
            set { this.consenter = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"choice"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_cerx_v01_r04_3.Iehr.Repc_mt000012ca.IChoice Choice {
            get { return this.choice; }
            set { this.choice = value; }
        }

    }

}