/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 16:47:15 -0300 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Pharmacy.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged;
    using System;
    using System.Collections.Generic;


    /**
     * <summary>PORX_MT020030CA.SupplyEvent: Prescription Dispense 
     * Response</summary>
     * 
     * <remarks><p>Represents the information returned when a 
     * dispense has been accepted</p> <p>Allows communication of 
     * the identifiers assigned to the dispense and the 
     * prescription by the DIS.</p> PORX_MT020020CA.SupplyEvent: 
     * Dispense Pickup <p>Captures information about what 
     * prescription was picked up and who received it.</p> <p>The 
     * root class for the message. The time of pickup is specified 
     * on the ControlAct wrapper.</p> PORX_MT020050CA.SupplyEvent: 
     * Office Supply <p>This is the detailed information about a 
     * medication being supplied for office use.</p> <p>Allows for 
     * tracking of medications supplied to an office.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PORX_MT020020CA.SupplyEvent","PORX_MT020030CA.SupplyEvent","PORX_MT020050CA.SupplyEvent"})]
    public class PrescriptionDispenseResponse : MessagePartBean {

        private II id;
        private SET<II, Identifier> inFulfillmentOfActRequestId;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.RelatedPerson receiverPersonalRelationship;
        private TS effectiveTime;
        private PQ quantity;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.Dispensed product;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.ServiceDeliveryLocation destinationServiceDeliveryLocation;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Pharmacy.Merged.SupplyOrder fulfillmentSupplyRequest;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.Includes subjectOf;

        public PrescriptionDispenseResponse() {
            this.id = new IIImpl();
            this.inFulfillmentOfActRequestId = new SETImpl<II, Identifier>(typeof(IIImpl));
            this.effectiveTime = new TSImpl();
            this.quantity = new PQImpl();
        }
        /**
         * <summary>A:Local Dispense ID</summary>
         * 
         * <remarks><p>Identifier assigned by the dispensing 
         * facility.</p> <p>Allows formal tracking of centrally 
         * recorded dispenses to local records for audit and related 
         * purposes.</p> Dispense Id <p>Identity of prescription 
         * dispense that has been picked up.</p> <p>Allows dispenses to 
         * be uniquely identified. This attribute is mandatory because 
         * the identity of the dispense record must be known.</p> 
         * Dispense Identifier <p>Identifier of a dispense event to be 
         * used by the requesting dispenser.</p> <p>Establishes a 
         * record of impending dispense on the prescription. Attribute 
         * is mandatory to ensure that successful request to dispense 
         * has been acknowledged by the DIS.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"id"})]
        public Identifier Id {
            get { return this.id.Value; }
            set { this.id.Value = value; }
        }

        /**
         * <summary>PrescriptionOrderNumber</summary>
         * 
         * <remarks>A:Prescription Order Number <p>This is an 
         * identifier assigned to a specific medication order. The 
         * number remains constant across the lifetime of the order, 
         * regardless of the number of providers or pharmacies involved 
         * in fulfilling the order.</p> <p>Allows prescriptions to be 
         * uniquely referenced. Multiple identifiers are allowed to 
         * support assigning of prescription ids by the prescriber, 
         * EHR, and potentially by pharmacies.</p><p>The ID is 
         * mandatory to allow every prescription record to be uniquely 
         * identified.</p> <p>Allows prescriptions to be uniquely 
         * referenced. Multiple identifiers are allowed to support 
         * assigning of prescription ids by the prescriber, EHR, and 
         * potentially by pharmacies.</p><p>The ID is mandatory to 
         * allow every prescription record to be uniquely 
         * identified.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"inFulfillmentOf/actRequest/id"})]
        public ICollection<Identifier> InFulfillmentOfActRequestId {
            get { return this.inFulfillmentOfActRequestId.RawSet(); }
        }

        [Hl7XmlMappingAttribute(new string[] {"receiver/personalRelationship"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.RelatedPerson ReceiverPersonalRelationship {
            get { return this.receiverPersonalRelationship; }
            set { this.receiverPersonalRelationship = value; }
        }

        /**
         * <summary>SupplyDate</summary>
         * 
         * <remarks>A:Supply Date <p>Represents the date medication was 
         * supplied.</p> <p>Needed for audit purposes.</p><p>Because 
         * the supply date is always known, the attribute is 
         * mandatory.</p> <p>Needed for audit purposes.</p><p>Because 
         * the supply date is always known, the attribute is 
         * mandatory.</p> <p>Must be able to post date a dispense 
         * (enter retroactively) e.g. system failure</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"effectiveTime"})]
        public PlatformDate EffectiveTime {
            get { return this.effectiveTime.Value; }
            set { this.effectiveTime.Value = value; }
        }

        /**
         * <summary>SuppliedQuantity</summary>
         * 
         * <remarks>B:Supplied Quantity <p>The amount of medication 
         * that has been dispensed. Includes unit of measure.</p> 
         * <p>Allows for auditing of medication dispensed to an office. 
         * This is mandatory to allow reconciliation with the amount 
         * used from the office.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"quantity"})]
        public PhysicalQuantity Quantity {
            get { return this.quantity.Value; }
            set { this.quantity.Value = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"product"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.Dispensed Product {
            get { return this.product; }
            set { this.product = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"destination/serviceDeliveryLocation"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.ServiceDeliveryLocation DestinationServiceDeliveryLocation {
            get { return this.destinationServiceDeliveryLocation; }
            set { this.destinationServiceDeliveryLocation = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"fulfillment/supplyRequest"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Pharmacy.Merged.SupplyOrder FulfillmentSupplyRequest {
            get { return this.fulfillmentSupplyRequest; }
            set { this.fulfillmentSupplyRequest = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.Includes SubjectOf {
            get { return this.subjectOf; }
            set { this.subjectOf = value; }
        }

    }

}