/**
 * Copyright 2013 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2013-03-08 11:06:36 -0500 (Fri, 08 Mar 2013) $
 * Revision:      $LastChangedRevision: 6699 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r01.Claims.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Model;
    using System;


    [Hl7PartTypeMappingAttribute(new string[] {"COCT_MT290000CA.PatientEncounter","COCT_MT300000CA.PatientEncounter"})]
    public class PatientEncounter : MessagePartBean {

        private II id;
        private TS effectiveTime;

        public PatientEncounter() {
            this.id = new IIImpl();
            this.effectiveTime = new TSImpl();
        }
        /**
         * <summary>Un-merged Business Name: (no business name 
         * specified)</summary>
         * 
         * <remarks>Relationship: COCT_MT300000CA.PatientEncounter.id 
         * Conformance/Cardinality: POPULATED (1) <p>encounter id</p> 
         * Un-merged Business Name: (no business name specified) 
         * Relationship: COCT_MT290000CA.PatientEncounter.id 
         * Conformance/Cardinality: POPULATED (1) <p>Encounter id</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"id"})]
        public Identifier Id {
            get { return this.id.Value; }
            set { this.id.Value = value; }
        }

        /**
         * <summary>Un-merged Business Name: (no business name 
         * specified)</summary>
         * 
         * <remarks>Relationship: 
         * COCT_MT300000CA.PatientEncounter.effectiveTime 
         * Conformance/Cardinality: REQUIRED (0-1) <p>admit/discharge 
         * date</p> Un-merged Business Name: (no business name 
         * specified) Relationship: 
         * COCT_MT290000CA.PatientEncounter.effectiveTime 
         * Conformance/Cardinality: REQUIRED (0-1) <p>admit/discharge 
         * date</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"effectiveTime"})]
        public PlatformDate EffectiveTime {
            get { return this.effectiveTime.Value; }
            set { this.effectiveTime.Value = value; }
        }

    }

}