/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: jmis $
 * Last modified: $LastChangedDate: 2015-09-15 10:17:45 -0400 (Tue, 15 Sep 2015) $
 * Revision:      $LastChangedRevision: 9774 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Pharmacy.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Common.Coct_mt090108ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Merged;


    /**
     * <summary>Business Name: PrescriptionReference</summary>
     * 
     * <remarks>PORX_MT020070CA.SubstanceAdministrationRequest: 
     * Prescription Reference <p>The Prescriber Name must be 
     * specified only when the Prescription Order Number is 
     * Null.</p> <p>Component MUST be specified if the id is null 
     * and CAN NOT be specified if the id is not null</p> 
     * <p>Dispenses for electronically created prescriptions must 
     * reference the prescription.</p> <p>Information pertaining to 
     * the prescription for which a dispense is being created</p> 
     * PORX_MT060010CA.SupplyRequest: Prescription Reference 
     * <p>Links a dispense with its parent prescription.</p> <p>A 
     * reference to the prescription order being dispensed</p> 
     * PORX_MT060090CA.SubstanceAdministrationRequest: Prescription 
     * Reference <p>Links a dispense with its parent 
     * prescription.</p> <p>A reference to the prescription order 
     * being dispensed</p> PORX_MT020060CA.DeviceRequest: 
     * Prescription Reference <p>The Prescriber Name must be 
     * specified only when the Prescription ID is Null</p> 
     * <p>Dispenses for electronically created prescriptions must 
     * reference the prescription.</p> <p>Information pertaining to 
     * the prescription for which a dispense is being created</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PORX_MT020060CA.DeviceRequest","PORX_MT020070CA.SubstanceAdministrationRequest","PORX_MT060010CA.SupplyRequest","PORX_MT060090CA.SubstanceAdministrationRequest"})]
    public class PrescriptionReference : MessagePartBean {

        private II id;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Common.Coct_mt090108ca.HealthcareWorker responsiblePartyAssignedEntity;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Merged.RefusedBy author;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Pharmacy.Merged.Component6 component;

        public PrescriptionReference() {
            this.id = new IIImpl();
        }
        /**
         * <summary>Business Name: PrescriptionOrderNumber</summary>
         * 
         * <remarks>Un-merged Business Name: PrescriptionOrderNumber 
         * Relationship: 
         * PORX_MT020070CA.SubstanceAdministrationRequest.id 
         * Conformance/Cardinality: REQUIRED (1) <p>Allows 
         * prescriptions to be uniquely referenced.</p><p>The ID is 
         * only 'populated' because in some cases the prescription will 
         * not yet exist electronically.</p> <p>The identifier of the 
         * prescription for which a dispense is being created.</p> 
         * Un-merged Business Name: PrescriptionOrderNumber 
         * Relationship: PORX_MT060010CA.SupplyRequest.id 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows 
         * prescriptions to be uniquely referenced and associated with 
         * the dispense.</p><p>The ID is mandatory because the DIS will 
         * always assign a Prescription Order Number.</p> <p>This is an 
         * identifier assigned to a specific device order. The number 
         * remains constant across the lifetime of the order, 
         * regardless of the number of providers or pharmacies involved 
         * in fulfilling the order.</p> Un-merged Business Name: 
         * PrescriptionOrderNumber Relationship: 
         * PORX_MT060090CA.SubstanceAdministrationRequest.id 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows 
         * prescriptions to be uniquely referenced and associated with 
         * the dispense.</p><p>The ID is mandatory because the DIS will 
         * always assign a Prescription Order Number.</p> <p>This is an 
         * identifier assigned to a specific medication order. The 
         * number remains constant across the lifetime of the order, 
         * regardless of the number of providers or pharmacies involved 
         * in fulfilling the order.</p> Un-merged Business Name: 
         * PrescriptionOrderNumber Relationship: 
         * PORX_MT020060CA.DeviceRequest.id Conformance/Cardinality: 
         * REQUIRED (1) <p>Allows prescriptions to be uniquely 
         * referenced.</p><p>The ID is only 'populated' because in some 
         * cases the prescription will not yet exist 
         * electronically.</p> <p>The identifier of the prescription 
         * for which a dispense is beiing created.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"id"})]
        public Identifier Id {
            get { return this.id.Value; }
            set { this.id.Value = value; }
        }

        /**
         * <summary>Un-merged Business Name: (no business name 
         * specified)</summary>
         * 
         * <remarks>Relationship: 
         * PORX_MT020070CA.ResponsibleParty3.assignedEntity 
         * Conformance/Cardinality: REQUIRED (1) Un-merged Business 
         * Name: (no business name specified) Relationship: 
         * PORX_MT060010CA.ResponsibleParty3.assignedEntity 
         * Conformance/Cardinality: REQUIRED (1) Un-merged Business 
         * Name: (no business name specified) Relationship: 
         * PORX_MT060090CA.ResponsibleParty3.assignedEntity 
         * Conformance/Cardinality: REQUIRED (1) Un-merged Business 
         * Name: (no business name specified) Relationship: 
         * PORX_MT020060CA.ResponsibleParty3.assignedEntity 
         * Conformance/Cardinality: REQUIRED (1)</remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"responsibleParty/assignedEntity"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Common.Coct_mt090108ca.HealthcareWorker ResponsiblePartyAssignedEntity {
            get { return this.responsiblePartyAssignedEntity; }
            set { this.responsiblePartyAssignedEntity = value; }
        }

        /**
         * <summary>Un-merged Business Name: (no business name 
         * specified)</summary>
         * 
         * <remarks>Relationship: 
         * PORX_MT020070CA.SubstanceAdministrationRequest.author 
         * Conformance/Cardinality: REQUIRED (0-1) Un-merged Business 
         * Name: (no business name specified) Relationship: 
         * PORX_MT060010CA.SupplyRequest.author 
         * Conformance/Cardinality: MANDATORY (1) Un-merged Business 
         * Name: (no business name specified) Relationship: 
         * PORX_MT060090CA.SubstanceAdministrationRequest.author 
         * Conformance/Cardinality: MANDATORY (1) Un-merged Business 
         * Name: (no business name specified) Relationship: 
         * PORX_MT020060CA.DeviceRequest.author 
         * Conformance/Cardinality: REQUIRED (0-1)</remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"author"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Merged.RefusedBy Author {
            get { return this.author; }
            set { this.author = value; }
        }

        /**
         * <summary>Un-merged Business Name: (no business name 
         * specified)</summary>
         * 
         * <remarks>Relationship: 
         * PORX_MT020070CA.SubstanceAdministrationRequest.component 
         * Conformance/Cardinality: REQUIRED (0-1)</remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"component"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Pharmacy.Merged.Component6 Component {
            get { return this.component; }
            set { this.component = value; }
        }

    }

}