/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2012-01-18 21:09:22 -0500 (Wed, 18 Jan 2012) $
 * Revision:      $LastChangedRevision: 3983 $
 */

/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Lab.Polb_mt004100ca {
    using Ca.Infoway.Messagebuilder;
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Lab.Merged;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged;
    using System;
    using System.Collections.Generic;


    /**
     * <summary>Isolate Observations</summary>
     * 
     * <remarks><p>Allows for further observations to be 
     * documentation at the isolate level, e.g. growth, colony 
     * count, etc.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"POLB_MT004100CA.IsolateObservationEvent"})]
    public class IsolateObservations : MessagePartBean {

        private CD isolateObservationType;
        private CS isolateObservationStatus;
        private IVL<TS, Interval<PlatformDate>> isolateObservationEffectiveTime;
        private ST isolateObservationValue;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged.Includes> subjectOf1;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Lab.Merged.ResultStatusProcessStep subjectOf2ResultStatusProcessStep;

        public IsolateObservations() {
            this.isolateObservationType = new CDImpl();
            this.isolateObservationStatus = new CSImpl();
            this.isolateObservationEffectiveTime = new IVLImpl<TS, Interval<PlatformDate>>();
            this.isolateObservationValue = new STImpl();
            this.subjectOf1 = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged.Includes>();
        }
        /**
         * <summary>Isolate Observation Type</summary>
         * 
         * <remarks><p>Describes the type of isolate observation and is 
         * bound to the LOINC code domain.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public Code IsolateObservationType {
            get { return (Code) this.isolateObservationType.Value; }
            set { this.isolateObservationType.Value = value; }
        }

        /**
         * <summary>Isolate Observation Status</summary>
         * 
         * <remarks><p>Status associated with the Isolate 
         * Observation.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"statusCode"})]
        public ActStatus IsolateObservationStatus {
            get { return (ActStatus) this.isolateObservationStatus.Value; }
            set { this.isolateObservationStatus.Value = value; }
        }

        /**
         * <summary>Isolate Observation Effective Time</summary>
         * 
         * <remarks><p>Effective time of the Isolate Observation.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"effectiveTime"})]
        public Interval<PlatformDate> IsolateObservationEffectiveTime {
            get { return this.isolateObservationEffectiveTime.Value; }
            set { this.isolateObservationEffectiveTime.Value = value; }
        }

        /**
         * <summary>Isolate Observation Value</summary>
         * 
         * <remarks><p>The value of the isolate observation.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"value"})]
        public String IsolateObservationValue {
            get { return this.isolateObservationValue.Value; }
            set { this.isolateObservationValue.Value = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf1"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged.Includes> SubjectOf1 {
            get { return this.subjectOf1; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf2/resultStatusProcessStep"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Lab.Merged.ResultStatusProcessStep SubjectOf2ResultStatusProcessStep {
            get { return this.subjectOf2ResultStatusProcessStep; }
            set { this.subjectOf2ResultStatusProcessStep = value; }
        }

    }

}