/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 16:47:15 -0300 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Repc_mt500003ca {
    using Ca.Infoway.Messagebuilder;
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt050202ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged;
    using System;
    using System.Collections.Generic;


    /**
     * <summary>Care Composition</summary>
     * 
     * <remarks><p>A care composition is a record with two 
     * purposes. It indicates that care of a given type has 
     * occurred or is occurring. It also acts as a collector for 
     * the events that happened during care, including who is 
     * responsible for the care provided.</p><p>Care composition 
     * messages may be sent during the course of care to describe 
     * the progress of care or may be sent at the termination of 
     * care to describe all the activities that occurred during the 
     * provision of care. Note that this record merely captures the 
     * existence of care and the locations and people involved. The 
     * actual discrete events and any care summary documentation 
     * that results are captured using other 
     * messages.</p><p>Examples include: encounters, 
     * condition-related care (episodes) and longer-term care 
     * collections such as &quot;gynecological care&quot;.</p> <p>A 
     * care composition is a record with two purposes. It indicates 
     * that care of a given type has occurred or is occurring. It 
     * also acts as a collector for the events that happened during 
     * care, including who is responsible for the care 
     * provided.</p><p>Care composition messages may be sent during 
     * the course of care to describe the progress of care or may 
     * be sent at the termination of care to describe all the 
     * activities that occurred during the provision of care. Note 
     * that this record merely captures the existence of care and 
     * the locations and people involved. The actual discrete 
     * events and any care summary documentation that results are 
     * captured using other messages.</p><p>Examples include: 
     * encounters, condition-related care (episodes) and 
     * longer-term care collections such as &quot;gynecological 
     * care&quot;.</p> <p>A care composition is a record with two 
     * purposes. It indicates that care of a given type has 
     * occurred or is occurring. It also acts as a collector for 
     * the events that happened during care, including who is 
     * responsible for the care provided.</p><p>Care composition 
     * messages may be sent during the course of care to describe 
     * the progress of care or may be sent at the termination of 
     * care to describe all the activities that occurred during the 
     * provision of care. Note that this record merely captures the 
     * existence of care and the locations and people involved. The 
     * actual discrete events and any care summary documentation 
     * that results are captured using other 
     * messages.</p><p>Examples include: encounters, 
     * condition-related care (episodes) and longer-term care 
     * collections such as &quot;gynecological care&quot;.</p> 
     * <p>Care compositions allow grouping together numerous 
     * related records which aids searching and navigation. Also, 
     * the mere knowledge that a type of care has occurred or is 
     * occurring (e.g. an in-patient hospital encounter) can be 
     * useful information when delivering subsequent care.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"REPC_MT500003CA.PatientCareProvisionEvent"})]
    public class CareComposition : MessagePartBean, Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Comt_mt111111ca.ISHR {

        private II id;
        private CV code;
        private BL negationInd;
        private CS statusCode;
        private IVL<TS, Interval<PlatformDate>> effectiveTime;
        private SET<CV, Code> confidentialityCode;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.SpecimenRole subject1Specimen;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt050202ca.Patient> subject2Patient;
        private INT subject3PatientPatientEntityQuantifiedKindQuantity;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson responsiblePartyActingPerson;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson> performerActingPerson;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.ChangedBy author;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.IActingPerson informantActingPerson;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson dischargerActingPerson;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.EHRRepository custodian1AssignedDevice;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.ServiceLocation custodian2ServiceDeliveryLocation;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.OccurredAt> location;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.DischargeDiagnosis> outcomeDiagnosisEvent;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.Request_1 inFulfillmentOfActRequest;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.OldPatientCareProvisionEvent> predecessorOldPatientCareProvisionEvent;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.BecauseOf> reason;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.NewPatientCareProvisionEvent successorNewPatientCareProvisionEvent;
        private BL subjectOf1AnnotationIndicator;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.ControlActEvent subjectOf2ControlActEvent;
        private IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.CareCompositions> componentOfPatientCareProvisionEvent;

        public CareComposition() {
            this.id = new IIImpl();
            this.code = new CVImpl();
            this.negationInd = new BLImpl();
            this.statusCode = new CSImpl();
            this.effectiveTime = new IVLImpl<TS, Interval<PlatformDate>>();
            this.confidentialityCode = new SETImpl<CV, Code>(typeof(CVImpl));
            this.subject2Patient = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt050202ca.Patient>();
            this.subject3PatientPatientEntityQuantifiedKindQuantity = new INTImpl();
            this.performerActingPerson = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson>();
            this.location = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.OccurredAt>();
            this.outcomeDiagnosisEvent = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.DischargeDiagnosis>();
            this.predecessorOldPatientCareProvisionEvent = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.OldPatientCareProvisionEvent>();
            this.reason = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.BecauseOf>();
            this.subjectOf1AnnotationIndicator = new BLImpl(false);
            this.componentOfPatientCareProvisionEvent = new List<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.CareCompositions>();
        }
        /**
         * <summary>A: Care Composition Id</summary>
         * 
         * <remarks></p> </p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"id"})]
        public Identifier Id {
            get { return this.id.Value; }
            set { this.id.Value = value; }
        }

        /**
         * <summary>B: Care Composition Type</summary>
         * 
         * <remarks></p><p>Care Composition is the generic name given 
         * to event 'containers' such as Encounters, 
         * Health-Condition-based Collections (Episodes) and Care-based 
         * Collections. The &quot;type&quot; of care composition places 
         * constraints on what elements are 
         * supported.</p><p>Encounter-based collection: a series of 
         * health care events that occur during an interaction between 
         * one or more health care providers and one or more patients 
         * where the providers and the patient remain in the same 
         * location over a contiguous period of time; the providers and 
         * patient may be at different locations (telehealth). e.g. 
         * Inpatient encounter, Community 
         * encounter.</p><p>Condition-based collection (Episode): a 
         * series of interactions between a patient and one or more 
         * health care providers over time in one or more locations and 
         * tied together by a common diagnosis or 
         * problem.</p><p>Care-based collection: a high level grouping 
         * of health events, encounters, and/or episodes related to a 
         * particular area of healthcare. e.g. Gynecology care, 
         * Cardiology Care, etc.</p> </p><p>Care Composition is the 
         * generic name given to event 'containers' such as Encounters, 
         * Health-Condition-based Collections (Episodes) and Care-based 
         * Collections. The &quot;type&quot; of care composition places 
         * constraints on what elements are 
         * supported.</p><p>Encounter-based collection: a series of 
         * health care events that occur during an interaction between 
         * one or more health care providers and one or more patients 
         * where the providers and the patient remain in the same 
         * location over a contiguous period of time; the providers and 
         * patient may be at different locations (telehealth). e.g. 
         * Inpatient encounter, Community 
         * encounter.</p><p>Condition-based collection (Episode): a 
         * series of interactions between a patient and one or more 
         * health care providers over time in one or more locations and 
         * tied together by a common diagnosis or 
         * problem.</p><p>Care-based collection: a high level grouping 
         * of health events, encounters, and/or episodes related to a 
         * particular area of healthcare. e.g. Gynecology care, 
         * Cardiology Care, etc.</p> </p><p>Care Composition is the 
         * generic name given to event 'containers' such as Encounters, 
         * Health-Condition-based Collections (Episodes) and Care-based 
         * Collections. The &quot;type&quot; of care composition places 
         * constraints on what elements are 
         * supported.</p><p>Encounter-based collection: a series of 
         * health care events that occur during an interaction between 
         * one or more health care providers and one or more patients 
         * where the providers and the patient remain in the same 
         * location over a contiguous period of time; the providers and 
         * patient may be at different locations (telehealth). e.g. 
         * Inpatient encounter, Community 
         * encounter.</p><p>Condition-based collection (Episode): a 
         * series of interactions between a patient and one or more 
         * health care providers over time in one or more locations and 
         * tied together by a common diagnosis or 
         * problem.</p><p>Care-based collection: a high level grouping 
         * of health events, encounters, and/or episodes related to a 
         * particular area of healthcare. e.g. Gynecology care, 
         * Cardiology Care, etc.</p> </p><p>Care Composition is the 
         * generic name given to event 'containers' such as Encounters, 
         * Health-Condition-based Collections (Episodes) and Care-based 
         * Collections. The &quot;type&quot; of care composition places 
         * constraints on what elements are 
         * supported.</p><p>Encounter-based collection: a series of 
         * health care events that occur during an interaction between 
         * one or more health care providers and one or more patients 
         * where the providers and the patient remain in the same 
         * location over a contiguous period of time; the providers and 
         * patient may be at different locations (telehealth). e.g. 
         * Inpatient encounter, Community 
         * encounter.</p><p>Condition-based collection (Episode): a 
         * series of interactions between a patient and one or more 
         * health care providers over time in one or more locations and 
         * tied together by a common diagnosis or 
         * problem.</p><p>Care-based collection: a high level grouping 
         * of health events, encounters, and/or episodes related to a 
         * particular area of healthcare. e.g. Gynecology care, 
         * Cardiology Care, etc.</p> </p><p>Care Composition is the 
         * generic name given to event 'containers' such as Encounters, 
         * Health-Condition-based Collections (Episodes) and Care-based 
         * Collections. The &quot;type&quot; of care composition places 
         * constraints on what elements are 
         * supported.</p><p>Encounter-based collection: a series of 
         * health care events that occur during an interaction between 
         * one or more health care providers and one or more patients 
         * where the providers and the patient remain in the same 
         * location over a contiguous period of time; the providers and 
         * patient may be at different locations (telehealth). e.g. 
         * Inpatient encounter, Community 
         * encounter.</p><p>Condition-based collection (Episode): a 
         * series of interactions between a patient and one or more 
         * health care providers over time in one or more locations and 
         * tied together by a common diagnosis or 
         * problem.</p><p>Care-based collection: a high level grouping 
         * of health events, encounters, and/or episodes related to a 
         * particular area of healthcare. e.g. Gynecology care, 
         * Cardiology Care, etc.</p> </p> </p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public ActCareEventType Code {
            get { return (ActCareEventType) this.code.Value; }
            set { this.code.Value = value; }
        }

        /**
         * <summary>D:Refuted Indicator</summary>
         * 
         * <remarks><p>Refuted Indicator cannot be specified unless 
         * Care Composition Type is Encounter or a specialization 
         * there-of.</p> </p> </p> </p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"negationInd"})]
        public bool? NegationInd {
            get { return this.negationInd.Value; }
            set { this.negationInd.Value = value; }
        }

        /**
         * <summary>C: Care Composition Status</summary>
         * 
         * <remarks></p> </p> </p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"statusCode"})]
        public ActStatus StatusCode {
            get { return (ActStatus) this.statusCode.Value; }
            set { this.statusCode.Value = value; }
        }

        /**
         * <summary>F: Care Composition Period</summary>
         * 
         * <remarks><p>Represents the start and end of the date/time 
         * interval during which the care described by the composition 
         * was/is being provided.</p><p>E.g. The admission and 
         * discharge date/time; the date on which the episode began and 
         * ended; etc.</p><p>Please note that it is possible for many 
         * episodes and care events to not have an end date; in these 
         * situations, only the start date will be specified. Even 
         * encounters will not have an end date until the encounter is 
         * completed/patient is discharged.</p> <p>Represents the start 
         * and end of the date/time interval during which the care 
         * described by the composition was/is being 
         * provided.</p><p>E.g. The admission and discharge date/time; 
         * the date on which the episode began and ended; 
         * etc.</p><p>Please note that it is possible for many episodes 
         * and care events to not have an end date; in these 
         * situations, only the start date will be specified. Even 
         * encounters will not have an end date until the encounter is 
         * completed/patient is discharged.</p> <p>Represents the start 
         * and end of the date/time interval during which the care 
         * described by the composition was/is being 
         * provided.</p><p>E.g. The admission and discharge date/time; 
         * the date on which the episode began and ended; 
         * etc.</p><p>Please note that it is possible for many episodes 
         * and care events to not have an end date; in these 
         * situations, only the start date will be specified. Even 
         * encounters will not have an end date until the encounter is 
         * completed/patient is discharged.</p> </p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"effectiveTime"})]
        public Interval<PlatformDate> EffectiveTime {
            get { return this.effectiveTime.Value; }
            set { this.effectiveTime.Value = value; }
        }

        /**
         * <summary>E: Care Composition Masking Indicators</summary>
         * 
         * <remarks></p><p>Masking a care composition record masks it 
         * for all associated patients (i.e. all patients involved in 
         * the care composition as a group).</p><p>Also, masking a care 
         * composition implicitly masks all records associated with 
         * that care composition.</p> </p><p>Masking a care composition 
         * record masks it for all associated patients (i.e. all 
         * patients involved in the care composition as a 
         * group).</p><p>Also, masking a care composition implicitly 
         * masks all records associated with that care composition.</p> 
         * </p><p>Masking a care composition record masks it for all 
         * associated patients (i.e. all patients involved in the care 
         * composition as a group).</p><p>Also, masking a care 
         * composition implicitly masks all records associated with 
         * that care composition.</p> </p><p>Masking a care composition 
         * record masks it for all associated patients (i.e. all 
         * patients involved in the care composition as a 
         * group).</p><p>Also, masking a care composition implicitly 
         * masks all records associated with that care composition.</p> 
         * </p><p>Masking a care composition record masks it for all 
         * associated patients (i.e. all patients involved in the care 
         * composition as a group).</p><p>Also, masking a care 
         * composition implicitly masks all records associated with 
         * that care composition.</p> </p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"confidentialityCode"})]
        public ICollection<x_BasicConfidentialityKind> ConfidentialityCode {
            get { return this.confidentialityCode.RawSet<x_BasicConfidentialityKind>(); }
        }

        [Hl7XmlMappingAttribute(new string[] {"subject1/specimen"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.SpecimenRole Subject1Specimen {
            get { return this.subject1Specimen; }
            set { this.subject1Specimen = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subject2/patient"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt050202ca.Patient> Subject2Patient {
            get { return this.subject2Patient; }
        }

        /**
         * <summary>J:Number of Patients</summary>
         * 
         * <remarks><p>Indicates the number of patients involved in a 
         * group encounter. For non-group encounters, this attribute 
         * will always be &quot;1&quot;.</p> <p>Allows a provider to 
         * ascertain the size of a group encounter without necessarily 
         * revealing the identity of the patients involved.</p><p>The 
         * patients associated with an encounter must be specified at 
         * the time the record is created, thus the number of patients 
         * will always be known, making this element mandatory.</p> 
         * <p>Allows a provider to ascertain the size of a group 
         * encounter without necessarily revealing the identity of the 
         * patients involved.</p><p>The patients associated with an 
         * encounter must be specified at the time the record is 
         * created, thus the number of patients will always be known, 
         * making this element mandatory.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"subject3/patient/patientEntityQuantifiedKind/quantity"})]
        public int? Subject3PatientPatientEntityQuantifiedKindQuantity {
            get { return this.subject3PatientPatientEntityQuantifiedKindQuantity.Value; }
            set { this.subject3PatientPatientEntityQuantifiedKindQuantity.Value = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"responsibleParty/actingPerson"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson ResponsiblePartyActingPerson {
            get { return this.responsiblePartyActingPerson; }
            set { this.responsiblePartyActingPerson = value; }
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker ResponsiblePartyActingPersonAsAssignedEntity1 {
            get { return this.responsiblePartyActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker) this.responsiblePartyActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker) null; }
        }
        public bool HasResponsiblePartyActingPersonAsAssignedEntity1() {
            return (this.responsiblePartyActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker);
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization ResponsiblePartyActingPersonAsAssignedEntity2 {
            get { return this.responsiblePartyActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization) this.responsiblePartyActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization) null; }
        }
        public bool HasResponsiblePartyActingPersonAsAssignedEntity2() {
            return (this.responsiblePartyActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization);
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson ResponsiblePartyActingPersonAsPersonalRelationship {
            get { return this.responsiblePartyActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson) this.responsiblePartyActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson) null; }
        }
        public bool HasResponsiblePartyActingPersonAsPersonalRelationship() {
            return (this.responsiblePartyActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson);
        }

        [Hl7XmlMappingAttribute(new string[] {"performer/actingPerson"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson> PerformerActingPerson {
            get { return this.performerActingPerson; }
        }

        [Hl7XmlMappingAttribute(new string[] {"author"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.ChangedBy Author {
            get { return this.author; }
            set { this.author = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"informant/actingPerson"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.IActingPerson InformantActingPerson {
            get { return this.informantActingPerson; }
            set { this.informantActingPerson = value; }
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker InformantActingPersonAsAssignedEntity1 {
            get { return this.informantActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker) this.informantActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker) null; }
        }
        public bool HasInformantActingPersonAsAssignedEntity1() {
            return (this.informantActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker);
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization InformantActingPersonAsAssignedEntity2 {
            get { return this.informantActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization) this.informantActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization) null; }
        }
        public bool HasInformantActingPersonAsAssignedEntity2() {
            return (this.informantActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization);
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.Patient_2 InformantActingPersonAsPatient {
            get { return this.informantActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.Patient_2 ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.Patient_2) this.informantActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.Patient_2) null; }
        }
        public bool HasInformantActingPersonAsPatient() {
            return (this.informantActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.Patient_2);
        }

        [Hl7XmlMappingAttribute(new string[] {"discharger/actingPerson"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt911108ca.IActingPerson DischargerActingPerson {
            get { return this.dischargerActingPerson; }
            set { this.dischargerActingPerson = value; }
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker DischargerActingPersonAsAssignedEntity1 {
            get { return this.dischargerActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker) this.dischargerActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker) null; }
        }
        public bool HasDischargerActingPersonAsAssignedEntity1() {
            return (this.dischargerActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.HealthcareWorker);
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization DischargerActingPersonAsAssignedEntity2 {
            get { return this.dischargerActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization) this.dischargerActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization) null; }
        }
        public bool HasDischargerActingPersonAsAssignedEntity2() {
            return (this.dischargerActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt090508ca.HealthcareOrganization);
        }

        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson DischargerActingPersonAsPersonalRelationship {
            get { return this.dischargerActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson ? (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson) this.dischargerActingPerson : (Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson) null; }
        }
        public bool HasDischargerActingPersonAsPersonalRelationship() {
            return (this.dischargerActingPerson is Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Coct_mt910108ca.RelatedPerson);
        }

        [Hl7XmlMappingAttribute(new string[] {"custodian1/assignedDevice"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.EHRRepository Custodian1AssignedDevice {
            get { return this.custodian1AssignedDevice; }
            set { this.custodian1AssignedDevice = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"custodian2/serviceDeliveryLocation"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Common.Merged.ServiceLocation Custodian2ServiceDeliveryLocation {
            get { return this.custodian2ServiceDeliveryLocation; }
            set { this.custodian2ServiceDeliveryLocation = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"location"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.OccurredAt> Location {
            get { return this.location; }
        }

        [Hl7XmlMappingAttribute(new string[] {"outcome/diagnosisEvent"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.DischargeDiagnosis> OutcomeDiagnosisEvent {
            get { return this.outcomeDiagnosisEvent; }
        }

        [Hl7XmlMappingAttribute(new string[] {"inFulfillmentOf/actRequest"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.Request_1 InFulfillmentOfActRequest {
            get { return this.inFulfillmentOfActRequest; }
            set { this.inFulfillmentOfActRequest = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"predecessor/oldPatientCareProvisionEvent"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.OldPatientCareProvisionEvent> PredecessorOldPatientCareProvisionEvent {
            get { return this.predecessorOldPatientCareProvisionEvent; }
        }

        [Hl7XmlMappingAttribute(new string[] {"reason"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.BecauseOf> Reason {
            get { return this.reason; }
        }

        [Hl7XmlMappingAttribute(new string[] {"successor/newPatientCareProvisionEvent"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.NewPatientCareProvisionEvent SuccessorNewPatientCareProvisionEvent {
            get { return this.successorNewPatientCareProvisionEvent; }
            set { this.successorNewPatientCareProvisionEvent = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf1/annotationIndicator"})]
        public bool? SubjectOf1AnnotationIndicator {
            get { return this.subjectOf1AnnotationIndicator.Value; }
            set { this.subjectOf1AnnotationIndicator.Value = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf2/controlActEvent"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Iehr.Merged.ControlActEvent SubjectOf2ControlActEvent {
            get { return this.subjectOf2ControlActEvent; }
            set { this.subjectOf2ControlActEvent = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"componentOf/patientCareProvisionEvent"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Merged.CareCompositions> ComponentOfPatientCareProvisionEvent {
            get { return this.componentOfPatientCareProvisionEvent; }
        }

    }

}