/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: jmis $
 * Last modified: $LastChangedDate: 2015-09-15 11:09:53 -0400 (Tue, 15 Sep 2015) $
 * Revision:      $LastChangedRevision: 9796 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Pharmacy.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged;
    using System;


    /**
     * <summary>PORX_MT020070CA.SupplyRequest: (no business name)</summary>
     * 
     * <p>Important in understanding the patient's treatment. May 
     * also be required by the EHR repository.</p> <p>Additional 
     * information about the prescription being fulfilled.</p> 
     * PORX_MT020060CA.SupplyRequest2: (no business name) <p>At 
     * least one of Total Prescribed Quantity and Total Days Supply 
     * must be present and not Null.</p> <p>Important in 
     * understanding the patient's treatment. May also be required 
     * by the EHR repository.</p> <p>Additional information about 
     * the prescription being fulfilled.</p>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PORX_MT020060CA.SupplyRequest2","PORX_MT020070CA.SupplyRequest","PORX_MT060190CA.SupplyRequest"})]
    public class SupplyRequest : MessagePartBean {

        private CS statusCode;
        private PQ quantity;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged.TargetedToPharmacy location;
        private INT repeatNumber;
        private IVL<TS, Interval<PlatformDate>> expectedUseTime;

        public SupplyRequest() {
            this.statusCode = new CSImpl();
            this.quantity = new PQImpl();
            this.repeatNumber = new INTImpl();
            this.expectedUseTime = new IVLImpl<TS, Interval<PlatformDate>>();
        }
        /**
         * <summary>Business Name: PrescriptionDispensableIndicator</summary>
         * 
         * <remarks>Un-merged Business Name: 
         * PrescriptionDispensableIndicator Relationship: 
         * PORX_MT060190CA.SupplyRequest.statusCode 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows the 
         * dispensing authorization of the prescription to be 
         * controlled/manipulates as needed.</p><p>Attribute is marked 
         * as &quot;mandatory&quot; as the dispensing authority of the 
         * prescription will always be known.</p> <p>This generally 
         * mirrors the status for the prescription, but in some 
         * circumstances may be changed to 'aborted' while the 
         * prescription is still active. When this occurs, it means the 
         * prescription may no longer be dispensed, though it may still 
         * be administered.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"statusCode"})]
        public ActStatus StatusCode {
            get { return (ActStatus) this.statusCode.Value; }
            set { this.statusCode.Value = value; }
        }

        /**
         * <summary>Business Name: TotalPrescribedQuantity</summary>
         * 
         * <remarks>Un-merged Business Name: TotalPrescribedQuantity 
         * Relationship: PORX_MT060190CA.SupplyRequest.quantity 
         * Conformance/Cardinality: REQUIRED (0-1) <p>Sets upper limit 
         * for medication to be dispensed. Can be used to verify the 
         * intention of the prescriber with respect to the overall 
         * medication. Used for comparison when determining whether 
         * additional quantity may be dispensed in the context of a 
         * part-fill prescription.</p> <p>The overall amount of amount 
         * medication to be dispensed under this prescription. Includes 
         * any first fills (trials, aligning quantities), the initial 
         * standard fill plus all refills.</p> Un-merged Business Name: 
         * TotalPrescribedQuantity Relationship: 
         * PORX_MT020070CA.SupplyRequest.quantity 
         * Conformance/Cardinality: REQUIRED (0-1) <p>Critical in 
         * understanding the patient's medication profile, both past 
         * and current. This also allows determination of the amount 
         * that remains to be dispensed against the prescription.</p> 
         * <p>The overall amount of amount medication to be dispensed 
         * under this prescription. Includes any first fills (trials, 
         * aligning quantities), the initial standard fill plus all 
         * refills.</p> Un-merged Business Name: 
         * TotalPrescribedQuantity Relationship: 
         * PORX_MT020060CA.SupplyRequest2.quantity 
         * Conformance/Cardinality: REQUIRED (0-1) <p>Critical in 
         * understanding the patient's profile, both past and current. 
         * This also allows determination of the amount that remains to 
         * be dispensed against the prescription.</p> <p>The overall 
         * amount to be dispensed under this prescription. Includes the 
         * initial standard fill plus all refills</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"quantity"})]
        public PhysicalQuantity Quantity {
            get { return this.quantity.Value; }
            set { this.quantity.Value = value; }
        }

        /**
         * <summary>Un-merged Business Name: (no business name 
         * specified)</summary>
         * 
         * <remarks>Relationship: 
         * PORX_MT060190CA.SupplyRequest.location 
         * Conformance/Cardinality: REQUIRED (1)</remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"location"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Merged.TargetedToPharmacy Location {
            get { return this.location; }
            set { this.location = value; }
        }

        /**
         * <summary>Business Name: NumberOfAuthorizedFills</summary>
         * 
         * <remarks>Un-merged Business Name: NumberOfAuthorizedFills 
         * Relationship: PORX_MT020070CA.SupplyRequest.repeatNumber 
         * Conformance/Cardinality: REQUIRED (0-1) <p>Regulation 
         * prevents this number from being calculated in some 
         * jurisdictions.</p> <p>Records the total number of fills 
         * authorized</p> Un-merged Business Name: 
         * NumberOfAuthorizedFills Relationship: 
         * PORX_MT020060CA.SupplyRequest2.repeatNumber 
         * Conformance/Cardinality: REQUIRED (0-1) <p>Regulation 
         * prevents this number from being calculated in some 
         * jurisdictions.</p> <p>Records the total number of fills 
         * authorized</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"repeatNumber"})]
        public int? RepeatNumber {
            get { return this.repeatNumber.Value; }
            set { this.repeatNumber.Value = value; }
        }

        /**
         * <summary>Business Name: TotalDaysSupply</summary>
         * 
         * <remarks>Un-merged Business Name: TotalDaysSupply 
         * Relationship: PORX_MT020070CA.SupplyRequest.expectedUseTime 
         * Conformance/Cardinality: MANDATORY (1) <p>Useful in 
         * monitoring patient compliance. May also be useful in 
         * determining and managing certain contraindications 
         * ('Fill-Too-Soon', 'Fill-Too-Late', and 'Duration of 
         * Therapy').</p><p>As it should always be known and for the 
         * reasons cited, the attribute is Mandatory.</p> <p>The number 
         * of days that the overall prescribed item is expected to 
         * last, if the patient is compliant with the dispensing and 
         * administration of the prescription.</p> Un-merged Business 
         * Name: TotalDaysSupply Relationship: 
         * PORX_MT020060CA.SupplyRequest2.expectedUseTime 
         * Conformance/Cardinality: REQUIRED (0-1) <p>Useful in 
         * monitoring patient compliance. May also be useful in 
         * determining and managing certain contraindications 
         * ('Fill-Too-Soon', 'Fill-Too-Late', and 'Duration of 
         * Therapy').</p> <p>The number of days that the overall 
         * prescribed item is expected to last, if the patient is 
         * compliant with the dispensing and use of the 
         * prescription.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"expectedUseTime"})]
        public Interval<PlatformDate> ExpectedUseTime {
            get { return this.expectedUseTime.Value; }
            set { this.expectedUseTime.Value = value; }
        }

    }

}