/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 16:47:15 -0300 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Repc_mt000005ca {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Common.Coct_mt090107ca;
    using Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Common.Merged;
    using Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Merged;
    using Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged;
    using System;
    using System.Collections.Generic;


    /**
     * <summary>Allergy/Intolerance</summary>
     * 
     * <remarks><p>Value is mandatory if not using SNOMED</p> <p>A 
     * record of a patient's allergy or intolerance.</p> 
     * <p>Necessary component of a person's overall medication and 
     * clinical profile. Helps with drug contraindication 
     * checking.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"REPC_MT000005CA.IntoleranceCondition"})]
    public class AllergyIntolerance : MessagePartBean {

        private II id;
        private CD code;
        private BL negationInd;
        private CS statusCode;
        private TS effectiveTime;
        private CV confidentialityCode;
        private CV uncertaintyCode;
        private CV value;
        private Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Common.Merged.Patient subjectPatient;
        private Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Common.Coct_mt090107ca.Provider responsiblePartyAssignedPerson;
        private Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.RefusedBy author;
        private Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Merged.ReportedBy informant;
        private Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.RecordedAt location;
        private IList<Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Merged.IRecords> supportRecords;
        private IList<Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.Comment> subjectOf1Annotation;
        private Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.AllergyIntoleranceSeverityLevel subjectOf2SeverityObservation;
        private BL subjectOf3AnnotationIndicator;

        public AllergyIntolerance() {
            this.id = new IIImpl();
            this.code = new CDImpl();
            this.negationInd = new BLImpl();
            this.statusCode = new CSImpl();
            this.effectiveTime = new TSImpl();
            this.confidentialityCode = new CVImpl();
            this.uncertaintyCode = new CVImpl();
            this.value = new CVImpl();
            this.supportRecords = new List<Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Merged.IRecords>();
            this.subjectOf1Annotation = new List<Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.Comment>();
            this.subjectOf3AnnotationIndicator = new BLImpl(false);
        }
        /**
         * <summary>D:Allergy/Intolerance Record Id</summary>
         * 
         * <remarks><p>Unique identifier for an allergy/intolerance 
         * record.</p> <p>Allows for direct referencing of an 
         * allergy/intolerance record when querying or performing 
         * updates and is therefore mandatory.</p> <p>This is the 
         * identifier of the allergy/intolerance record.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"id"})]
        public Identifier Id {
            get { return this.id.Value; }
            set { this.id.Value = value; }
        }

        /**
         * <summary>A:Allergy/Intolerance Type</summary>
         * 
         * <remarks><p>A coded value denoting whether the record 
         * pertains to an intolerance or a true allergy. (Allergies 
         * result from immunologic reactions. Intolerances do not.)</p> 
         * <p>Allows for the separation of allergy and intolerance 
         * records. The type of condition is critical to understanding 
         * the record and is therefore mandatory. It is expressed as a 
         * CD to allow for SNOMED post-coordination.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public ObservationIntoleranceType Code {
            get { return (ObservationIntoleranceType) this.code.Value; }
            set { this.code.Value = value; }
        }

        /**
         * <summary>G:Allergy/Intolerance Refuted</summary>
         * 
         * <remarks><p>An indication that the allergy/intolerance has 
         * been refuted. I.e. A clinician has positively determined 
         * that the patient does not suffer from a particular allergy 
         * or intolerance.</p> <p>Allows providers to refute a 
         * previously confirmed or suspected allergy. The attribute is 
         * mandatory because it is critical to know whether the record 
         * represents the refutation or affirmation of an allergy or 
         * intolerance.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"negationInd"})]
        public bool? NegationInd {
            get { return this.negationInd.Value; }
            set { this.negationInd.Value = value; }
        }

        /**
         * <summary>E:Allergy/Intolerance Status</summary>
         * 
         * <remarks><p>A coded value that indicates whether an 
         * allergy/intolerance is 'ACTIVE' or 'COMPLETE' (indicating no 
         * longer active).</p> <p>Allows providers to evaluate the 
         * relevance of a recorded allergy/intolerance. The status has 
         * a default value of 'ACTIVE' and is therefore mandatory.</p> 
         * <p>System must default the status to 'ACTIVE'.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"statusCode"})]
        public ActStatus StatusCode {
            get { return (ActStatus) this.statusCode.Value; }
            set { this.statusCode.Value = value; }
        }

        /**
         * <summary>I:Allergy/Intolerance Date</summary>
         * 
         * <remarks></p> <p>Allows providers to evaluate the period of 
         * relevance for the allergy/intolerance record.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"effectiveTime"})]
        public PlatformDate EffectiveTime {
            get { return this.effectiveTime.Value; }
            set { this.effectiveTime.Value = value; }
        }

        /**
         * <summary>H:Allergy/Intolerance Masking Indicator</summary>
         * 
         * <remarks><p>This indicates whether the allergy is masked or 
         * not.</p> <p>Provides support for additional confidentiality 
         * constraint to reflect the wishes of the patient.</p><p>The 
         * attribute is optional because not all systems will support 
         * masking.</p> <p>Provides support for additional 
         * confidentiality constraint to reflect the wishes of the 
         * patient.</p><p>The attribute is optional because not all 
         * systems will support masking.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"confidentialityCode"})]
        public x_VeryBasicConfidentialityKind ConfidentialityCode {
            get { return (x_VeryBasicConfidentialityKind) this.confidentialityCode.Value; }
            set { this.confidentialityCode.Value = value; }
        }

        /**
         * <summary>F:Confirmed Indicator</summary>
         * 
         * <remarks><p>An indication of the level of confidence/surety 
         * placed in the recorded information.</p><p>The two valid 
         * codes are:</p><p>- U (stated with uncertainty) -Specifies 
         * that the author of the act affirms the uncertainty of the 
         * act statement. In other words, they know that parts of the 
         * act statement are not certain or are inferred. An example of 
         * this is an inferred prescription where some order data is 
         * inferred from a supply event (i.e. dispense).</p><p>- N 
         * (stated with no assertion of uncertainty) - Specifies that 
         * the act statement is made without any explicit expression of 
         * certainty/uncertainty. This is the normal statement, meaning 
         * that it may not be free of errors and uncertainty may still 
         * exist. In healthcare, N is believed to express certainty to 
         * the strength possible.</p><p>An allergy or intolerance 
         * record is always used in drug contraindication checking 
         * whether the record is U or N.</p> <p>An indication of the 
         * level of confidence/surety placed in the recorded 
         * information.</p><p>The two valid codes are:</p><p>- U 
         * (stated with uncertainty) -Specifies that the author of the 
         * act affirms the uncertainty of the act statement. In other 
         * words, they know that parts of the act statement are not 
         * certain or are inferred. An example of this is an inferred 
         * prescription where some order data is inferred from a supply 
         * event (i.e. dispense).</p><p>- N (stated with no assertion 
         * of uncertainty) - Specifies that the act statement is made 
         * without any explicit expression of certainty/uncertainty. 
         * This is the normal statement, meaning that it may not be 
         * free of errors and uncertainty may still exist. In 
         * healthcare, N is believed to express certainty to the 
         * strength possible.</p><p>An allergy or intolerance record is 
         * always used in drug contraindication checking whether the 
         * record is U or N.</p> <p>An indication of the level of 
         * confidence/surety placed in the recorded 
         * information.</p><p>The two valid codes are:</p><p>- U 
         * (stated with uncertainty) -Specifies that the author of the 
         * act affirms the uncertainty of the act statement. In other 
         * words, they know that parts of the act statement are not 
         * certain or are inferred. An example of this is an inferred 
         * prescription where some order data is inferred from a supply 
         * event (i.e. dispense).</p><p>- N (stated with no assertion 
         * of uncertainty) - Specifies that the act statement is made 
         * without any explicit expression of certainty/uncertainty. 
         * This is the normal statement, meaning that it may not be 
         * free of errors and uncertainty may still exist. In 
         * healthcare, N is believed to express certainty to the 
         * strength possible.</p><p>An allergy or intolerance record is 
         * always used in drug contraindication checking whether the 
         * record is U or N.</p> <p>An indication of the level of 
         * confidence/surety placed in the recorded 
         * information.</p><p>The two valid codes are:</p><p>- U 
         * (stated with uncertainty) -Specifies that the author of the 
         * act affirms the uncertainty of the act statement. In other 
         * words, they know that parts of the act statement are not 
         * certain or are inferred. An example of this is an inferred 
         * prescription where some order data is inferred from a supply 
         * event (i.e. dispense).</p><p>- N (stated with no assertion 
         * of uncertainty) - Specifies that the act statement is made 
         * without any explicit expression of certainty/uncertainty. 
         * This is the normal statement, meaning that it may not be 
         * free of errors and uncertainty may still exist. In 
         * healthcare, N is believed to express certainty to the 
         * strength possible.</p><p>An allergy or intolerance record is 
         * always used in drug contraindication checking whether the 
         * record is U or N.</p> <p>An indication of the level of 
         * confidence/surety placed in the recorded 
         * information.</p><p>The two valid codes are:</p><p>- U 
         * (stated with uncertainty) -Specifies that the author of the 
         * act affirms the uncertainty of the act statement. In other 
         * words, they know that parts of the act statement are not 
         * certain or are inferred. An example of this is an inferred 
         * prescription where some order data is inferred from a supply 
         * event (i.e. dispense).</p><p>- N (stated with no assertion 
         * of uncertainty) - Specifies that the act statement is made 
         * without any explicit expression of certainty/uncertainty. 
         * This is the normal statement, meaning that it may not be 
         * free of errors and uncertainty may still exist. In 
         * healthcare, N is believed to express certainty to the 
         * strength possible.</p><p>An allergy or intolerance record is 
         * always used in drug contraindication checking whether the 
         * record is U or N.</p> <p>Helps other providers to make 
         * appropriate decisions in their management of allergy or 
         * intolerance contraindications.</p><p>Attribute is mandatory 
         * because an allergy or intolerance record must be tagged as 
         * either 'confirmed' or 'suspected'.</p> <p>Helps other 
         * providers to make appropriate decisions in their management 
         * of allergy or intolerance contraindications.</p><p>Attribute 
         * is mandatory because an allergy or intolerance record must 
         * be tagged as either 'confirmed' or 'suspected'.</p> 
         * <p>&nbsp;This can be &lsquo;N&rsquo; or &lsquo;U&rsquo;.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"uncertaintyCode"})]
        public ActUncertainty UncertaintyCode {
            get { return (ActUncertainty) this.uncertaintyCode.Value; }
            set { this.uncertaintyCode.Value = value; }
        }

        /**
         * <summary>B:Agent</summary>
         * 
         * <remarks><p>Indicates the substance to which the patient is 
         * allergic</p> <p>Critical for identifying the allergy or 
         * intolerance. Because it is not used for SNOMED, this element 
         * is optional.</p> <p>&nbsp;Because PIN is not using SNOMED, 
         * this attribute&nbsp;is mandatory.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"value"})]
        public IntoleranceValue Value {
            get { return (IntoleranceValue) this.value.Value; }
            set { this.value.Value = value; }
        }

        /**
         * <summary>Suffered By</summary>
         * 
         * <remarks><p>&nbsp;Identifies the person suffering from 
         * the&nbsp;allergy/intolerance.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"subject/patient"})]
        public Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Common.Merged.Patient SubjectPatient {
            get { return this.subjectPatient; }
            set { this.subjectPatient = value; }
        }

        /**
         * <summary>Supervised By</summary>
         * 
         * <remarks><p>&nbsp;Identifies the provider who is taking 
         * responsibility for&nbsp;the actions of the author.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"responsibleParty/assignedPerson"})]
        public Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Common.Coct_mt090107ca.Provider ResponsiblePartyAssignedPerson {
            get { return this.responsiblePartyAssignedPerson; }
            set { this.responsiblePartyAssignedPerson = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"author"})]
        public Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.RefusedBy Author {
            get { return this.author; }
            set { this.author = value; }
        }

        /**
         * <summary>Reported by</summary>
         * 
         * <remarks><div>Indicates where the information that led to 
         * the&nbsp;recording of this information came 
         * from.&nbsp;</div></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"informant"})]
        public Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Merged.ReportedBy Informant {
            get { return this.informant; }
            set { this.informant = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"location"})]
        public Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.RecordedAt Location {
            get { return this.location; }
            set { this.location = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"support/records"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Iehr.Merged.IRecords> SupportRecords {
            get { return this.supportRecords; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf1/annotation"})]
        public IList<Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.Comment> SubjectOf1Annotation {
            get { return this.subjectOf1Annotation; }
        }

        [Hl7XmlMappingAttribute(new string[] {"subjectOf2/severityObservation"})]
        public Ca.Infoway.Messagebuilder.Model.Sk_cerx_v01_r04_3.Merged.AllergyIntoleranceSeverityLevel SubjectOf2SeverityObservation {
            get { return this.subjectOf2SeverityObservation; }
            set { this.subjectOf2SeverityObservation = value; }
        }

        /**
         * <summary><div>This will only be present if the query 
         * indicated that&nbsp;notes were not to be returned and there 
         * are notes.</div></summary>
         */
        [Hl7XmlMappingAttribute(new string[] {"subjectOf3/annotationIndicator"})]
        public bool? SubjectOf3AnnotationIndicator {
            get { return this.subjectOf3AnnotationIndicator.Value; }
            set { this.subjectOf3AnnotationIndicator.Value = value; }
        }

    }

}