/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Ab_r02_04_03_shr.Common.Coct_mt050201ca {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Model;


    /**
     * <summary>Business Name: Patient</summary>
     * 
     * <p>Used when patienty identity confirmation is handled as a 
     * distinct business process rather than as part of each 
     * transaction. Allows transactions to be linked to a specific 
     * patient.</p> <p>A person who is receiving or may receive 
     * healthcare services and has had their identity previously 
     * confirmed</p>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"COCT_MT050201CA.Patient"})]
    public class Patient : MessagePartBean, Ca.Infoway.Messagebuilder.Model.Ab_r02_04_03_shr.Common.Merged.IPatient {

        private II id;

        public Patient() {
            this.id = new IIImpl();
        }
        /**
         * <summary>Business Name: A:Patient Identifier</summary>
         * 
         * <remarks>Relationship: COCT_MT050201CA.Patient.id 
         * Conformance/Cardinality: MANDATORY (1) <p>C39 
         * (Extension)</p> <p>PTT.050.01 (Extension)</p> <p>PTT.050.02 
         * (Root)</p> <p>A.1</p> <p>PID.2</p> <p>Patient.332-CY 
         * (Extension)</p> <p>Patient.331-CX (Root)</p> 
         * <p>Claim.330-CW</p> <p>Health Card Number</p> <p>PID.2</p> 
         * <p>PID.4</p> <p>ZDU.2</p> <p>ZKW.3</p> <p>Jurisdiction 
         * (Root)</p> <p>Person.PHN (Extension)</p> <p>Allows a patient 
         * to be referred to unambiguously. Because this is the 
         * principal mechanism for identifying patients to electronic 
         * systems, the attribute is mandatory.</p> <p>Unique 
         * identifier issued as part of the patient identity 
         * verification process.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"id"})]
        public Identifier Id {
            get { return this.id.Value; }
            set { this.id.Value = value; }
        }

    }

}