/**
 * Copyright 2013 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2013-03-08 11:06:36 -0500 (Fri, 08 Mar 2013) $
 * Revision:      $LastChangedRevision: 6699 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Interaction {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Common.Merged;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Common.Mfmi_mt700751ca;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Cr.Prpa_mt101101ca;


    /**
     * <summary>Business Name: PRPA_IN101105CA: Find Associated 
     * Person Identifiers Query</summary>
     * 
     * <p>This interaction sends a query to a Person Registry 
     * requesting all other identifiers associated with a specific 
     * person identifier.</p> Message: MCCI_MT002100CA.Message 
     * Control Act: MFMI_MT700751CA.ControlActEvent --> Payload: 
     * PRPA_MT101101CA.ParameterList
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PRPA_IN101105CA"})]
    public class FindAssociatedPersonIdentifiersQuery : HL7Message_1<Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Common.Mfmi_mt700751ca.TriggerEvent<Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r02.Cr.Prpa_mt101101ca.ParameterList>>, IInteraction {


        public FindAssociatedPersonIdentifiersQuery() {
        }
    }

}