/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 15:47:15 -0400 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_03.Immunization.Poiz_mt060140ca {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using System;
    using System.Collections.Generic;


    /**
     * <summary>Business Name: Immunization Query Parameters</summary>
     * 
     * <p>Root class for query.</p> <p>Defines the set of 
     * parameters that may be used to filter the query 
     * response.</p>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"POIZ_MT060140CA.ParameterList"})]
    public class ImmunizationQueryParameters : MessagePartBean {

        private II immunizationEventIDValue;
        private TS patientBirthDateValue;
        private CV patientGenderValue;
        private SET<II, Identifier> patientIDValue;
        private PN patientNameValue;

        public ImmunizationQueryParameters() {
            this.immunizationEventIDValue = new IIImpl();
            this.patientBirthDateValue = new TSImpl();
            this.patientGenderValue = new CVImpl();
            this.patientIDValue = new SETImpl<II, Identifier>(typeof(IIImpl));
            this.patientNameValue = new PNImpl();
        }
        /**
         * <summary>Business Name: A:Immunization Event ID</summary>
         * 
         * <remarks>Relationship: 
         * POIZ_MT060140CA.ImmunizationEventID.value 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows for 
         * filtering of queries by immuniation event ID. As a result, 
         * this attribute is mandatory.</p> <p>Specifies the identifier 
         * of the immunization event</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"immunizationEventID/value"})]
        public Identifier ImmunizationEventIDValue {
            get { return this.immunizationEventIDValue.Value; }
            set { this.immunizationEventIDValue.Value = value; }
        }

        /**
         * <summary>Business Name: E:Patient Birth Date</summary>
         * 
         * <remarks>Relationship: 
         * POIZ_MT060140CA.PatientBirthDate.value 
         * Conformance/Cardinality: MANDATORY (1) <p>Use to confirm 
         * identity of the patient for the query. As a result, this 
         * attribute is required.</p> <p>Indicates the date on which 
         * the patient was born.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"patientBirthDate/value"})]
        public PlatformDate PatientBirthDateValue {
            get { return this.patientBirthDateValue.Value; }
            set { this.patientBirthDateValue.Value = value; }
        }

        /**
         * <summary>Business Name: D:Patient Gender</summary>
         * 
         * <remarks>Relationship: POIZ_MT060140CA.PatientGender.value 
         * Conformance/Cardinality: MANDATORY (1) <p>Used to confirm 
         * the identity of the patient for the query. As a result, this 
         * attribute is required.</p> <p>Indicates the gender (sex) of 
         * the patient.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"patientGender/value"})]
        public AdministrativeGender PatientGenderValue {
            get { return (AdministrativeGender) this.patientGenderValue.Value; }
            set { this.patientGenderValue.Value = value; }
        }

        /**
         * <summary>Business Name: B:Patient Identifiers</summary>
         * 
         * <remarks>Relationship: POIZ_MT060140CA.PatientID.value 
         * Conformance/Cardinality: MANDATORY (1-5) <p>Allows filtering 
         * of result set by patient ID. This information is used to 
         * verify the record. As a result, this attribute is 
         * required.</p> <p>Identifier of the patient who is the 
         * subject of the patient immunization query. Filter the result 
         * set to include only those records pertaining to the patient 
         * with this Id.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"patientID/value"})]
        public ICollection<Identifier> PatientIDValue {
            get { return this.patientIDValue.RawSet(); }
        }

        /**
         * <summary>Business Name: C:Patient Name</summary>
         * 
         * <remarks>Relationship: POIZ_MT060140CA.PatientName.value 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows filtering 
         * of result set by patient name. This information is used to 
         * verify the record. As a result, this attribute is 
         * required.</p> <p>Names are messaged as iterations of the PN 
         * datatype, with specific name parts identified as a type 
         * declaration in addition to the text string.</p> <p>The name 
         * of the patient who is the subject of the patient 
         * immunization query.</p><p>Filter the result set to include 
         * only those records pertaining to the patient with this 
         * name.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"patientName/value"})]
        public PersonName PatientNameValue {
            get { return this.patientNameValue.Value; }
            set { this.patientNameValue.Value = value; }
        }

    }

}