/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 15:47:15 -0400 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Ab_r02_04_03_imm.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Model;
    using System;


    /**
     * <summary>Business Name: HealthcareWorker</summary>
     * 
     * <remarks>POIZ_MT060150AB.AssignedEntity: Healthcare Worker 
     * <p>Critical to tracking responsibility and performing 
     * follow-up. The CMET supports both licensed providers as well 
     * as non-licensed providers such as technicians, 
     * receptionists, etc.</p> <p>All attributes other than the 
     * various identifiers are expected to be retrieved from the 
     * provider registry.</p> <p>The person organization assigned 
     * to carry out the associated (linked by a participation) 
     * action and/or the organization under whose authority they 
     * are acting.</p> POIZ_MT030050AB.AssignedEntity: Healthcare 
     * Worker <p>Critical to tracking responsibility and performing 
     * follow-up. The CMET supports both licensed providers as well 
     * as non-licensed providers such as technicians, 
     * receptionists, etc.</p> <p>All attributes other than the 
     * various identifiers are expected to be retrieved from the 
     * provider registry.</p> <p>The person organization assigned 
     * to carry out the associated (linked by a participation) 
     * action and/or the organization under whose authority they 
     * are acting.</p> POIZ_MT030060AB.AssignedEntity: Healthcare 
     * Worker <p>Critical to tracking responsibility and performing 
     * follow-up. The CMET supports both licensed providers as well 
     * as non-licensed providers such as technicians, 
     * receptionists, etc.</p> <p>All attributes other than the 
     * various identifiers are expected to be retrieved from the 
     * provider registry.</p> <p>The person organization assigned 
     * to carry out the associated (linked by a participation) 
     * action and/or the organization under whose authority they 
     * are acting.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"COCT_MT260010CA.AssignedEntity","COCT_MT260020CA.AssignedEntity","COCT_MT260030CA.AssignedEntity","POIZ_MT030050AB.AssignedEntity","POIZ_MT030060AB.AssignedEntity","POIZ_MT060150AB.AssignedEntity"})]
    public class HealthcareWorker : MessagePartBean {

        private ST representedOrganizationName;
        private II representedOrganizationId;

        public HealthcareWorker() {
            this.representedOrganizationName = new STImpl();
            this.representedOrganizationId = new IIImpl();
        }
        /**
         * <summary>Un-merged Business Name: KnowledgebaseVendorName</summary>
         * 
         * <remarks>Relationship: COCT_MT260030CA.Organization.name 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows a 
         * knowledgebase vendor to be referenced by name.</p><p>The 
         * attribute is mandatory because it is the only information 
         * collected about a knowledgebase vendor.</p> <p>The name of a 
         * clinical knowledgebase vendor organization.</p> Un-merged 
         * Business Name: KnowledgebaseVendorName Relationship: 
         * COCT_MT260020CA.Organization.name Conformance/Cardinality: 
         * MANDATORY (1) Un-merged Business Name: 
         * KnowledgebaseVendorName Relationship: 
         * COCT_MT260010CA.Organization.name Conformance/Cardinality: 
         * MANDATORY (1) <p>Allows a knowledgebase vendor to be 
         * referenced by name.</p><p>The attribute is mandatory because 
         * it is the only information collected about a knowledgebase 
         * vendor.</p> <p>The name of a clinical knowledgebase vendor 
         * organization.</p> Un-merged Business Name: OrganizationName 
         * Relationship: POIZ_MT060150AB.Organization.name 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows for human 
         * recognition of the organization as well as confirmation of 
         * the identifier. As a result, the attribute is mandatory.</p> 
         * <p>Identifies the name of the organization</p> Un-merged 
         * Business Name: OrganizationName Relationship: 
         * POIZ_MT030050AB.Organization.name Conformance/Cardinality: 
         * MANDATORY (1) <p>Allows for human recognition of the 
         * organization as well as confirmation of the identifier. As a 
         * result, the attribute is mandatory.</p> <p>Identifies the 
         * name of the organization</p> Un-merged Business Name: 
         * OrganizationName Relationship: 
         * POIZ_MT030060AB.Organization.name Conformance/Cardinality: 
         * MANDATORY (1) <p>Allows for human recognition of the 
         * organization as well as confirmation of the identifier. As a 
         * result, the attribute is mandatory.</p> <p>Identifies the 
         * name of the organization</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"assignedOrganization/name","representedOrganization/name"})]
        [Hl7MapByPartType(Name="assignedOrganization", Type="COCT_MT260010CA.Organization")]
        [Hl7MapByPartType(Name="assignedOrganization", Type="COCT_MT260020CA.Organization")]
        [Hl7MapByPartType(Name="assignedOrganization", Type="COCT_MT260030CA.Organization")]
        [Hl7MapByPartType(Name="representedOrganization", Type="POIZ_MT030050AB.Organization")]
        [Hl7MapByPartType(Name="representedOrganization", Type="POIZ_MT030060AB.Organization")]
        [Hl7MapByPartType(Name="representedOrganization", Type="POIZ_MT060150AB.Organization")]
        public String RepresentedOrganizationName {
            get { return this.representedOrganizationName.Value; }
            set { this.representedOrganizationName.Value = value; }
        }

        /**
         * <summary>Business Name: OrganizationIdentifier</summary>
         * 
         * <remarks>Un-merged Business Name: OrganizationIdentifier 
         * Relationship: POIZ_MT060150AB.Organization.id 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows the 
         * organization to be referenced when determining privileges 
         * and for drill-downs to retrieve additional information. 
         * Because of its importance, the attribute is mandatory.</p> 
         * <p>A unique identifier for the organization</p> Un-merged 
         * Business Name: OrganizationIdentifier Relationship: 
         * POIZ_MT030050AB.Organization.id Conformance/Cardinality: 
         * MANDATORY (1) <p>Allows the organization to be referenced 
         * when determining privileges and for drill-downs to retrieve 
         * additional information. Because of its importance, the 
         * attribute is mandatory.</p> <p>A unique identifier for the 
         * organization</p> Un-merged Business Name: 
         * OrganizationIdentifier Relationship: 
         * POIZ_MT030060AB.Organization.id Conformance/Cardinality: 
         * MANDATORY (1) <p>Allows the organization to be referenced 
         * when determining privileges and for drill-downs to retrieve 
         * additional information. Because of its importance, the 
         * attribute is mandatory.</p> <p>A unique identifier for the 
         * organization</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"representedOrganization/id"})]
        public Identifier RepresentedOrganizationId {
            get { return this.representedOrganizationId.Value; }
            set { this.representedOrganizationId.Value = value; }
        }

    }

}