/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2012-02-16 11:06:56 -0500 (Thu, 16 Feb 2012) $
 * Revision:      $LastChangedRevision: 5470 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r01.Pharmacy.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using System;


    /**
     * <summary>GroupedWithin</summary>
     * 
     * <remarks>POME_MT010040CA.SpecializedKind: grouped within 
     * <p>Indicates the location of a medication in a particular 
     * abstract hierarchy. For example, what generic, generic 
     * formulation, or therapeutic class does the medication fall 
     * into.</p> <p>Exposes the drug hierarchy, allowing drill-down 
     * when prescribing and dispensing. Also indicates 
     * possibilities for substitution and can be important for 
     * detecting interactions such as allergies or duplicate 
     * therapy between closely-related drugs.</p> 
     * POME_MT010100CA.SpecializedKind: grouped within <p>Indicates 
     * the location of a medication in a particular abstract 
     * hierarchy. For example, what generic, generic formulation, 
     * or therapeutic class does the medication fall into.</p> 
     * <p>Exposes the drug hierarchy, allowing drill-down when 
     * prescribing and dispensing. Also indicates possibilities for 
     * substitution and can be important for detecting interactions 
     * such as allergies or duplicate therapy between 
     * closely-related drugs.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"POME_MT010040CA.SpecializedKind","POME_MT010100CA.SpecializedKind"})]
    public class GroupedWithin : MessagePartBean {

        private CV code;
        private CV generalizedMedicineClassCode;
        private ST generalizedMedicineClassName;

        public GroupedWithin() {
            this.code = new CVImpl();
            this.generalizedMedicineClassCode = new CVImpl();
            this.generalizedMedicineClassName = new STImpl();
        }
        /**
         * <summary>DrugCategoryCode</summary>
         * 
         * <remarks>Drug Category Code <p>A coded value denoting a 
         * specific level in the hierarchical definition of drugs.</p> 
         * <p>Describes the relationship between two levels of drug 
         * products (e.g. Drug A is the generic for Drug B)</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public MedicationGeneralizationRoleType Code {
            get { return (MedicationGeneralizationRoleType) this.code.Value; }
            set { this.code.Value = value; }
        }

        /**
         * <summary>DrugCode</summary>
         * 
         * <remarks>Drug Code <p>An identifier for a drug at a higher 
         * level of abstraction.</p> <p>Used to uniquely identify a 
         * particular drug product when prescribing/dispensing at a 
         * higher level of abstraction (e.g. generic drug, generic 
         * formulation).</p><p>This attribute is marked as 
         * &quot;populated&quot; as a drug code should be available in 
         * most cases.</p> <p>Used to uniquely identify a particular 
         * drug product when prescribing/dispensing at a higher level 
         * of abstraction (e.g. generic drug, generic 
         * formulation).</p><p>This attribute is marked as 
         * &quot;populated&quot; as a drug code should be available in 
         * most cases.</p> Drug Code <p>A code that uniquely 
         * identifiers a drug within a specific drug identification 
         * scheme.</p> <p>Used to uniquely identify a particular drug 
         * product when prescribing/dispensing at a higher level of 
         * abstraction (e.g. generic drug, generic 
         * formulation).</p><p>This attribute is marked as 
         * &quot;populated&quot; as drug code should be available in 
         * most cases.</p> <p>Used to uniquely identify a particular 
         * drug product when prescribing/dispensing at a higher level 
         * of abstraction (e.g. generic drug, generic 
         * formulation).</p><p>This attribute is marked as 
         * &quot;populated&quot; as drug code should be available in 
         * most cases.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"generalizedMedicineClass/code"})]
        public ClinicalDrug GeneralizedMedicineClassCode {
            get { return (ClinicalDrug) this.generalizedMedicineClassCode.Value; }
            set { this.generalizedMedicineClassCode.Value = value; }
        }

        /**
         * <summary>DrugName</summary>
         * 
         * <remarks>Drug Name <p>The name assigned to the drug at the 
         * higher level of abstraction.</p> <p>To display in dropdowns 
         * and for local searching.</p><p>This attribute is marked as 
         * &quot;populated&quot; as drug name should be available in 
         * most cases.</p> <p>To display in dropdowns and for local 
         * searching.</p><p>This attribute is marked as 
         * &quot;populated&quot; as drug name should be available in 
         * most cases.</p> Drug Name <p>The name assigned to a drug 
         * within a specific drug identification scheme.</p> <p>To 
         * display in dropdowns and for local searching.</p><p>This 
         * attribute is marked as &quot;populated&quot; as a drug name 
         * should be available in most cases.</p> <p>To display in 
         * dropdowns and for local searching.</p><p>This attribute is 
         * marked as &quot;populated&quot; as a drug name should be 
         * available in most cases.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"generalizedMedicineClass/name"})]
        public String GeneralizedMedicineClassName {
            get { return this.generalizedMedicineClassName.Value; }
            set { this.generalizedMedicineClassName.Value = value; }
        }

    }

}