/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 15:47:15 -0400 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_05_00.Pharmacy.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Datatype.Lang;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;
    using System;


    /**
     * <summary>Business Name: PrescriptionPatientMeasurements</summary>
     * 
     * <remarks>PORX_MT060340CA.QuantityObservationEvent: 
     * Prescription Patient Measurements <p>Allows patient height 
     * and weight to be conveyed to the pharmacy for dosage 
     * calculation or verification</p> <p>This comprises the height 
     * and/or weight of a patient as measured/observed/known by the 
     * prescriber at the time of prescribing.</p> 
     * PORX_MT010120CA.QuantityObservationEvent: Prescription 
     * Patient Measurements <p>Allows patient height and weight to 
     * be conveyed to the pharmacy for dosage calculation or 
     * verification;</p> <p>This comprises the height and/or weight 
     * of a patient as measured/observed/known by the prescriber at 
     * the time of prescribing.</p> 
     * PORX_MT060160CA.QuantityObservationEvent: Prescription 
     * Patient Measurements <p>Allows patient height and weight to 
     * be conveyed to the pharmacy for dosage calculation or 
     * verification</p> <p>This comprises the height and/or weight 
     * of a patient as measured/observed/known by the prescriber at 
     * the time of prescribing.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PORX_MT010120CA.QuantityObservationEvent","PORX_MT060160CA.QuantityObservationEvent","PORX_MT060340CA.QuantityObservationEvent"})]
    public class PrescriptionPatientMeasurements : MessagePartBean {

        private CV code;
        private TS effectiveTime;
        private PQ value;

        public PrescriptionPatientMeasurements() {
            this.code = new CVImpl();
            this.effectiveTime = new TSImpl();
            this.value = new PQImpl();
        }
        /**
         * <summary>Business Name: PrescriptionPatientMeasurementType</summary>
         * 
         * <remarks>Un-merged Business Name: 
         * PrescriptionPatientMeasurementType Relationship: 
         * PORX_MT060340CA.QuantityObservationEvent.code 
         * Conformance/Cardinality: MANDATORY (1) <p>Distinguishes 
         * height from weight.</p><p>Code is mandatory to ensure that 
         * measurements/observations are distinguishable.</p> 
         * <p>Identification of the type of observation that was made 
         * about the patient. The only two allowable types are height 
         * and weight.</p> Un-merged Business Name: 
         * PrescriptionPatientMeasurementType Relationship: 
         * PORX_MT010120CA.QuantityObservationEvent.code 
         * Conformance/Cardinality: MANDATORY (1) <p>Distinguishes what 
         * kind of information is being specified. Code is mandatory to 
         * ensure that measurements/observations are 
         * distinguishable.</p> <p>Identification of the type of 
         * measurement/observation that was made about the patient. The 
         * only two allowable types are height and weight.</p> 
         * Un-merged Business Name: PrescriptionPatientMeasurementType 
         * Relationship: PORX_MT060160CA.QuantityObservationEvent.code 
         * Conformance/Cardinality: MANDATORY (1) <p>Distinguishes 
         * height from weight.</p><p>Code is mandatory to ensure that 
         * measurements/observations are distinguishable.</p> 
         * <p>Identification of the type of observation that was made 
         * about the patient. The only two allowable types are height 
         * and weight.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public x_ActObservationHeightOrWeight Code {
            get { return (x_ActObservationHeightOrWeight) this.code.Value; }
            set { this.code.Value = value; }
        }

        /**
         * <summary>Un-merged Business Name: 
         * PrescriptionPatientMeasurementTime</summary>
         * 
         * <remarks>Relationship: 
         * PORX_MT060340CA.QuantityObservationEvent.effectiveTime 
         * Conformance/Cardinality: REQUIRED (1) <p>Allows provider to 
         * evaluate currency of the information.</p><p>The attribute is 
         * populated because the measurement time must be known or a 
         * null flavor must be specified.</p> <p>The date on which the 
         * measurement was made.</p> Un-merged Business Name: 
         * PrescriptionPatientMeasurementTimestamp Relationship: 
         * PORX_MT010120CA.QuantityObservationEvent.effectiveTime 
         * Conformance/Cardinality: REQUIRED (1) <p>Allows providers to 
         * evaluate currency of the information.</p><p>Because the date 
         * of measurement determines the relevance of the information, 
         * this attribute is defined as 'populated'.</p> <p>The date on 
         * which the measurement was made</p> Un-merged Business Name: 
         * PrescriptionPatientMeasurementTime Relationship: 
         * PORX_MT060160CA.QuantityObservationEvent.effectiveTime 
         * Conformance/Cardinality: REQUIRED (1) <p>Allows provider to 
         * evaluate currency of the information.</p><p>The attribute is 
         * populated because the measurement time must be known or a 
         * null flavor must be specified.</p> <p>The date on which the 
         * measurement was made.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"effectiveTime"})]
        public PlatformDate EffectiveTime {
            get { return this.effectiveTime.Value; }
            set { this.effectiveTime.Value = value; }
        }

        /**
         * <summary>Business Name: PrescriptionPatientMeasuredValue</summary>
         * 
         * <remarks>Un-merged Business Name: 
         * PrescriptionPatientMeasuredValue Relationship: 
         * PORX_MT060340CA.QuantityObservationEvent.value 
         * Conformance/Cardinality: MANDATORY (1) <p>OBS.010-02 
         * (quantity)</p> <p>OBS.010-03 (unit)</p> <p>Clinical.595-H4 
         * (value)</p> <p>Clinical.495-H3 (unit)</p> <p>Provides 
         * comparable representation of the measurement. May be used in 
         * calculations.</p><p>The attribute is mandatory because the 
         * measurement value must be known.</p> <p>The amount (quantity 
         * and unit) that has been recorded for the patient's height 
         * and/or weight. E.g. height in meters, weight in kilograms, 
         * etc.</p> Un-merged Business Name: 
         * PrescriptionPatientMeasuredValue Relationship: 
         * PORX_MT010120CA.QuantityObservationEvent.value 
         * Conformance/Cardinality: MANDATORY (1) <p>Provides 
         * comparable representation of the measurement. May be used in 
         * calculations.</p><p>Attribute is defined as 'mandatory' to 
         * ensure that a value is supplied, if there is a 
         * measurement.</p> <p>The amount (quantity and unit) that has 
         * been recorded for the specific type of observation. E.g. 
         * height in meters, weight in kilograms.</p> Un-merged 
         * Business Name: PrescriptionPatientMeasuredValue 
         * Relationship: PORX_MT060160CA.QuantityObservationEvent.value 
         * Conformance/Cardinality: MANDATORY (1) <p>OBS.010-02 
         * (quantity)</p> <p>OBS.010-03 (unit)</p> <p>Clinical.595-H4 
         * (value)</p> <p>Clinical.495-H3 (unit)</p> <p>Provides 
         * comparable representation of the measurement. May be used in 
         * calculations.</p><p>The attribute is mandatory because the 
         * measurement value must be known.</p> <p>The amount (quantity 
         * and unit) that has been recorded for the patient's height 
         * and/or weight. E.g. height in meters, weight in kilograms, 
         * etc.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"value"})]
        public PhysicalQuantity Value {
            get { return this.value.Value; }
            set { this.value.Value = value; }
        }

    }

}