/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 16:47:15 -0300 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Ab_mr2007_v02_r02.Cr.Merged {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Domainvalue;
    using Ca.Infoway.Messagebuilder.Model;


    /**
     * <summary>HasConfidenceValue</summary>
     * 
     * <remarks>PRPA_MT101104CA.Subject: *has confidence value 
     * <p>Associates the IDENT role with a required observation 
     * which indicates the confidence value of the returned 
     * record(s).</p> PRPA_MT101102CA.Subject: *has confidence 
     * value <p>Associates the IDENT role with a required 
     * observation which indicates the confidence value of the 
     * returned record(s).</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PRPA_MT101102CA.Subject","PRPA_MT101104CA.Subject"})]
    public class HasConfidenceValue : MessagePartBean {

        private CS typeCode;
        private Ca.Infoway.Messagebuilder.Model.Ab_mr2007_v02_r02.Cr.Merged.ConfidenceValue observationEvent;

        public HasConfidenceValue() {
            this.typeCode = new CSImpl();
        }
        [Hl7XmlMappingAttribute(new string[] {"typeCode"})]
        public ParticipationType TypeCode {
            get { return (ParticipationType) this.typeCode.Value; }
            set { this.typeCode.Value = value; }
        }

        [Hl7XmlMappingAttribute(new string[] {"observationEvent"})]
        public Ca.Infoway.Messagebuilder.Model.Ab_mr2007_v02_r02.Cr.Merged.ConfidenceValue ObservationEvent {
            get { return this.observationEvent; }
            set { this.observationEvent = value; }
        }

    }

}