#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["NetCoreConsoleApp/NetCoreConsoleApp.csproj", "NetCoreConsoleApp/"]
COPY ["message-builder-core/message-builder-core.csproj", "message-builder-core/"]
COPY ["message-builder-compatibility/message-builder-compatibility.csproj", "message-builder-compatibility/"]
COPY ["message-builder-xml/message-builder-xml.csproj", "message-builder-xml/"]
COPY ["message-builder-util/message-builder-util.csproj", "message-builder-util/"]
COPY ["message-builder-release-r02_04_03/message-builder-release-r02_04_03.csproj", "message-builder-release-r02_04_03/"]
RUN dotnet restore "NetCoreConsoleApp/NetCoreConsoleApp.csproj"
COPY . .
WORKDIR "/src/NetCoreConsoleApp"
RUN dotnet build "NetCoreConsoleApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NetCoreConsoleApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NetCoreConsoleApp.dll"]