namespace Ca.Infoway.Messagebuilder.Marshalling.HL7
{
	/// <author>Intelliware Development</author>
	public enum Hl7ErrorCode
	{
		UNSUPPORTED_INTERACTION,
		UNSUPPORTED_PROCESSING_ID,
		UNSUPPORTED_VERSION_ID,
		UNSUPPORTED_PROCESSING_MODE,
		UNKNOWN_SENDER,
		UNRECOGNIZED_ATTENTION_LINE,
		SYNTAX_ERROR,
		MANDATORY_FIELD_NOT_PROVIDED,
		REQUIRED_ATTRIBUTE_MISSING,
		DATA_TYPE_ERROR,
		VALUE_NOT_IN_CODE_SYSTEM,
		INVALID_CODE_SYSTEM_IN_CNE,
		NUMBER_OF_ASSOCIATIONS_EXCEEDS_LIMIT,
		NUMBER_OF_ATTRIBUTES_EXCEEDS_LIMIT,
		INTERNAL_ERROR,
		NO_STORAGE_SPACE_FOR_MESSAGE,
		MESSAGE_ROUTING_ERROR_DESTINATION_UNREACHABLE,
		MESSAGE_ROUTING_ERROR_DESTINATION_UNKNOWN,
		MESSAGE_ROUTING_WARNING_DESTINATION_UNREACHABLE,
		TL7_SYSTEM_ERROR,
		NOT_AUTHORIZED
	}
}
