/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: jmis $
 * Last modified: $LastChangedDate: 2015-09-15 11:09:53 -0400 (Tue, 15 Sep 2015) $
 * Revision:      $LastChangedRevision: 9796 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Lab.Polb_mt004000ca {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Domainvalue;
    using System;


    /**
     * <summary>Business Name: Reference Range Criteria</summary>
     * 
     * <p>Used for reference range criteria.</p> 
     * <p>ObservationEventCriterion allows for the identification 
     * of the parameters applied to the quoted interpretation range 
     * such as &quot;sex&quot;, &quot;age&quot;, etc.</p>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"POLB_MT004000CA.ObservationEventCriterion"})]
    public class ReferenceRangeCriteria : MessagePartBean {

        private CD code;
        private ST value;

        public ReferenceRangeCriteria() {
            this.code = new CDImpl();
            this.value = new STImpl();
        }
        /**
         * <summary>Business Name: Reference Range Criteria Type</summary>
         * 
         * <remarks>Relationship: 
         * POLB_MT004000CA.ObservationEventCriterion.code 
         * Conformance/Cardinality: REQUIRED (1) <p>The coded reference 
         * range criteria type.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public ObservationEventLabCriteriaType Code {
            get { return (ObservationEventLabCriteriaType) this.code.Value; }
            set { this.code.Value = value; }
        }

        /**
         * <summary>Business Name: Reference Range Criteria Value</summary>
         * 
         * <remarks>Relationship: 
         * POLB_MT004000CA.ObservationEventCriterion.value 
         * Conformance/Cardinality: REQUIRED (1) <p>The reference range 
         * criteria value.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"value"})]
        public String Value {
            get { return this.value.Value; }
            set { this.value.Value = value; }
        }

    }

}