/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2011-05-04 16:47:15 -0300 (Wed, 04 May 2011) $
 * Revision:      $LastChangedRevision: 2623 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Ab_mr2007_v02_r02.Pr.Prpm_mt309000ca {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Model;


    /**
     * <summary>Organization</summary>
     * 
     * <remarks><p>The scoping organization for the specified role 
     * class</p> <p>Supports the requirement to supply additional 
     * information regarding the assigning Organization of the 
     * specified RoleClass</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"PRPM_MT309000CA.Organization"})]
    public class Organization : MessagePartBean {

        private Ca.Infoway.Messagebuilder.Model.Ab_mr2007_v02_r02.Pr.Prpm_mt309000ca.TerritorialAuthority territorialAuthority;

        public Organization() {
        }
        [Hl7XmlMappingAttribute(new string[] {"territorialAuthority"})]
        public Ca.Infoway.Messagebuilder.Model.Ab_mr2007_v02_r02.Pr.Prpm_mt309000ca.TerritorialAuthority TerritorialAuthority {
            get { return this.territorialAuthority; }
            set { this.territorialAuthority = value; }
        }

    }

}