/**
 * Copyright 2012 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: tmcgrady $
 * Last modified: $LastChangedDate: 2012-02-16 11:03:02 -0500 (Thu, 16 Feb 2012) $
 * Revision:      $LastChangedRevision: 5415 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2007_v02_r01.Claims.Ficr_mt600201ca {
    using Ca.Infoway.Messagebuilder;
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Model;


    /**
     * <summary>Invoice Override details</summary>
     * 
     * <remarks><p>The reason or rationale for an Invoice Element 
     * override.</p> <p>Some overrides will require a text note 
     * component to fully explain the override.</p><p>If an 
     * adjudicator does not support the override (e.g. repeated 
     * service), the override code should not be ignored. In other 
     * words, the Invoice Grouping will likely be refused with a 
     * message &quot;we don't support this type of 
     * override&quot;.</p> <p>Some overrides will require a text 
     * note component to fully explain the override.</p><p>If an 
     * adjudicator does not support the override (e.g. repeated 
     * service), the override code should not be ignored. In other 
     * words, the Invoice Grouping will likely be refused with a 
     * message &quot;we don't support this type of 
     * override&quot;.</p> <p>RxS1: Not permitted for this 
     * scenario.</p></remarks>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"FICR_MT600201CA.InvoiceElementOverride"})]
    public class InvoiceOverrideDetails : MessagePartBean {

        private CV code;

        public InvoiceOverrideDetails() {
            this.code = new CVImpl();
        }
        /**
         * <summary>Invoice override code</summary>
         * 
         * <remarks><p>Coded responses that may occur as a result of 
         * the adjudication of an electronic invoice at a summary level 
         * and provides guidance on interpretation of the referenced 
         * adjudication results. i.e.. Subscriber Coverage Problem, 
         * Good Faith Indicator, Late Invoice</p> <p>This can be used 
         * for Xray to follow, paper to follow, etc.</p> <p>RxS1: Not 
         * permitted for this scenario.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"code"})]
        public Code Code {
            get { return (Code) this.code.Value; }
            set { this.code.Value = value; }
        }

    }

}