/**
 * Copyright 2015 Canada Health Infoway, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:        $LastChangedBy: jmis $
 * Last modified: $LastChangedDate: 2015-09-15 11:09:53 -0400 (Tue, 15 Sep 2015) $
 * Revision:      $LastChangedRevision: 9796 $
 */
/* This class was auto-generated by the message builder generator tools. */
namespace Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Iehr.Comt_mt300003ca {
    using Ca.Infoway.Messagebuilder.Annotation;
    using Ca.Infoway.Messagebuilder.Datatype;
    using Ca.Infoway.Messagebuilder.Datatype.Impl;
    using Ca.Infoway.Messagebuilder.Model;
    using Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Common.Coct_mt090108ca;
    using System;


    /**
     * <summary>Business Name: *b:annotated by</summary>
     * 
     * <p>Allows other providers to communicator with the author of 
     * the note for follow-up enquiries. The author of an 
     * annotation must always be known and is therefore 
     * mandatory.</p> <p>Identifier of the provider who created the 
     * patient note.</p>
     */
    [Hl7PartTypeMappingAttribute(new string[] {"COMT_MT300003CA.Author"})]
    public class AnnotatedBy : MessagePartBean {

        private TS time;
        private Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Common.Coct_mt090108ca.HealthcareWorker assignedEntity;

        public AnnotatedBy() {
            this.time = new TSImpl();
        }
        /**
         * <summary>Business Name: B:Patient Note Date</summary>
         * 
         * <remarks>Relationship: COMT_MT300003CA.Author.time 
         * Conformance/Cardinality: MANDATORY (1) <p>Allows other 
         * provider to evaluate the currency of the information 
         * contained in the note.</p><p>The date of the note creation 
         * is always known and is therefore mandatory.</p> <p>The date 
         * on which the patient note was created.</p></remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"time"})]
        public PlatformDate Time {
            get { return this.time.Value; }
            set { this.time.Value = value; }
        }

        /**
         * <summary>Relationship: COMT_MT300003CA.Author.assignedEntity</summary>
         * 
         * <remarks>Conformance/Cardinality: MANDATORY (1)</remarks>
         */
        [Hl7XmlMappingAttribute(new string[] {"assignedEntity"})]
        public Ca.Infoway.Messagebuilder.Model.Pcs_mr2009_r02_04_02.Common.Coct_mt090108ca.HealthcareWorker AssignedEntity {
            get { return this.assignedEntity; }
            set { this.assignedEntity = value; }
        }

    }

}